### ISSUE TITLE
Load Balancer is not building

### ISSUE THREAD

**Issue by DeshanKTD** [ThilinaManamgoda/serverless-architecture#2]
Check that issue and merge the files.
System service is build without errors

**Comment by ThilinaManamgoda** [comment]
It's because the Jetcd version that is used. Although i fixed the bug in Jetcd, it's not released yet as a mvn repo. So we have to use my repo instead. Fork this and install repo to local maven central. https://github.com/ThilinaManamgoda/jetcd. Also have to come up with a thread model that will run all the service at startup since there are several Main methods

**Comment by DeshanKTD** [comment]
A Warning pop as
```java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;```

Error pop as
```
ttestListCluster(com.coreos.jetcd.ClusterClientTest)  Time elapsed: 0.229 s  <<< FAILURE!
java.lang.AssertionError: Members: 4 expected [3] but found [4]
	at com.coreos.jetcd.ClusterClientTest.testListCluster(ClusterClientTest.java:34)

```
when building jetcd

**Comment by DeshanKTD** [comment]
That builds when maven install without tests
